apiVersion: v1
kind: Namespace
metadata:
  name: demo-etherpad-repos
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: github-redhat-sa-brazil-demo-summitgov-cy20
  namespace: demo-etherpad-repos
spec:
  type: GitHub
  pathname: https://github.com/redhat-sa-brazil/demo-summitgov-cy20.git
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-etherpad
  labels:
    app: demo-etherpad
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: demo-etherpad
  namespace: demo-etherpad
  labels:
    app: demo-etherpad
spec:
  clusterSelector:
    matchLabels:
      environment: development
  clusterReplicas: 1
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: demo-etherpad
  namespace: demo-etherpad
  labels:
    app: demo-etherpad
  annotations:
    apps.open-cluster-management.io/github-path: resources/application/demo-etherpad
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: demo-etherpad-repos/github-redhat-sa-brazil-demo-summitgov-cy20
  placement:
    placementRef:
      kind: PlacementRule
      name: demo-etherpad
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: demo-etherpad
  namespace: demo-etherpad
  labels:
    app: demo-etherpad
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - demo-etherpad