apiVersion: v1
kind: Namespace
metadata:
  name: demo-saude-digital-streams-repos
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: github-redhat-sa-brazil-demo-summitgov-cy20
  namespace: demo-saude-digital-streams-repos
spec:
  type: GitHub
  pathname: https://github.com/redhat-sa-brazil/demo-summitgov-cy20.git
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-saude-digital-streams
  labels:
    app: demo-saude-digital-streams
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: demo-saude-digital-streams
  namespace: demo-saude-digital-streams
  labels:
    app: demo-saude-digital-streams
spec:
  clusterSelector:
    matchLabels:
      environment: production
      priority: secondary
  clusterReplicas: 1
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: demo-saude-digital-streams
  namespace: demo-saude-digital-streams
  labels:
    app: demo-saude-digital-streams
  annotations:
    apps.open-cluster-management.io/github-path: resources/application/demo-saude-digital-streams
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: demo-saude-digital-streams-repos/github-redhat-sa-brazil-demo-summitgov-cy20
  placement:
    placementRef:
      kind: PlacementRule
      name: demo-saude-digital-streams
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: demo-saude-digital-streams
  namespace: demo-saude-digital-streams
  labels:
    app: demo-saude-digital-streams
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - demo-saude-digital-streams
