apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: openshift-operators-namespace
  namespace: open-cluster-management-policies
  annotations:
    policy.mcm.ibm.com/standards: NIST-CSF
    policy.mcm.ibm.com/categories: PR.IP Information Protection Processes and Procedures
    policy.mcm.ibm.com/controls: PR.IP-1 Baseline configuration
spec:
  complianceType: musthave
  remediationAction: inform
  disabled: false
  object-templates:
    - complianceType: musthave
      objectDefinition:
        kind: Namespace
        apiVersion: v1
        metadata:
          name: openshift-operators
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: binding-openshift-operators-namespace
  namespace: open-cluster-management-policies
placementRef:
  name: placement-openshift-operators-namespace
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: openshift-operators-namespace
  kind: Policy
  apiGroup: policy.mcm.ibm.com
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-openshift-operators-namespace
  namespace: open-cluster-management-policies
spec:
  clusterConditions:
  - type: OK
  clusterSelector:
    matchExpressions:
      - {key: vendor, operator: In, values: ["OpenShift"]}
