apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: global-iampolicy
  namespace: open-cluster-management-policies
  annotations:
    policy.mcm.ibm.com/standards: PCI, NIST-CSF
    policy.mcm.ibm.com/categories: DE.CM Security Continuous Monitoring, PR.DS DataSecurity, PR.AC Identity Management Authentication and Access Control
    policy.mcm.ibm.com/controls: DE.CM-8 Vulnerability scans, PR.DS-2 Data-in-transit, PR.AC-4 Access Control
spec:
  complianceType: musthave
  remediationAction: inform
  disabled: false
  namespaces:
    exclude: ["kube-*"]
    include: ["default"]
  policy-templates:
    - objectDefinition:
        apiVersion: iam.policies.ibm.com/v1alpha1
        kind: IamPolicy
        metadata:
          name: global-iampolicy-example
        spec:
          severity: medium
          namespaceSelector:
            include: ["*"]
            exclude: ["kube-*", "openshift-*"]
          remediationAction: inform
          maxClusterRoleBindingUsers: 5
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: binding-global-iampolicy
  namespace: open-cluster-management-policies
placementRef:
  name: placement-global-iampolicy
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: global-iampolicy
  kind: Policy
  apiGroup: policy.mcm.ibm.com
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-global-iampolicy
  namespace: open-cluster-management-policies
spec:
  clusterConditions:
  - type: OK
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["production", "quality", "development"]}
