kind: ConfigMap
apiVersion: v1
metadata:
  name: demo-etherpad-config
  namespace: demo-etherpad
data:
  settings.json: |
    {
      "title": "UBI Etherpad",
    
      "favicon": "favicon.ico",
    
      "skinName": "colibris",
    
      "ip": "0.0.0.0",
      "port": 9001,
    
      "showSettingsInAdminPage": false,

      "suppressErrorsInPadText": true,
    
      "dbType": "dirty",
      "dbSettings": {
        "filename": "data/dirty.db"
      },
    
      "defaultPadText" : "Welcome to Etherpad!\n\nThis pad text is synchronized as you type, so that everyone viewing this page sees the same text. This allows you to collaborate seamlessly on documents!\n\nGet involved with Etherpad at http:\/\/etherpad.org\n",
    
      "users": {
      },

      "padOptions": {
        "noColors":         false,
        "showControls":     true,
        "showChat":         true,
        "showLineNumbers":  true,
        "useMonospaceFont": false,
        "userName":         false,
        "userColor":        false,
        "rtl":              false,
        "alwaysShowChat":   false,
        "chatAndUsers":     false,
        "lang":             "en-gb"
      },
    
      "padShortcutEnabled" : {
        "altF9":     true,
        "altC":      true,
        "cmdShift2": true,
        "delete":    true,
        "return":    true,
        "esc":       true,
        "cmdS":      true,
        "tab":       true,
        "cmdZ":      true,
        "cmdY":      true,
        "cmdI":      true,
        "cmdB":      true,
        "cmdU":      true,
        "cmd5":      true,
        "cmdShiftL": true,
        "cmdShiftN": true,
        "cmdShift1": true,
        "cmdShiftC": true,
        "cmdH":      true,
        "ctrlHome":  true,
        "pageUp":    true,
        "pageDown":  true
      },
     
      "requireSession": false,
    
      "editOnly": false,
    
      "sessionNoPassword": false,
    
      "minify": true,
    
      "maxAge": 21600,
    
      "abiword": null,
    
      "soffice": null,
    
      "tidyHtml": null,
    
      "allowUnknownFileEnds": false,
    
      "requireAuthentication": false,
    
      "requireAuthorization": false,
    
      "trustProxy": false,
    
      "disableIPlogging": true,
    
      "automaticReconnectionTimeout": 0,
    
      "scrollWhenFocusLineIsOutOfViewport": {
    
        "percentage": {
          "editionAboveViewport": 0,
          "editionBelowViewport": 0
        },
    
        "duration": 0,
    
        "scrollWhenCaretIsInTheLastLineOfViewport": false,
    
        "percentageToScrollWhenUserPressesArrowUp": 0
      },

      "socketTransportProtocols" : ["xhr-polling", "jsonp-polling", "htmlfile"],
    
      "loadTest": false,
    
      "indentationOnNewLine": false,
    
      "toolbar": {
        "left": [
          ["bold", "italic", "underline", "strikethrough"],
          ["orderedlist", "unorderedlist", "indent", "outdent"],
          ["undo", "redo"],
          ["clearauthorship"]
        ],
        "right": [
          ["importexport", "timeslider", "savedrevision"],
          ["settings", "embed"],
          ["showusers"]
        ],
        "timeslider": [
          ["timeslider_export", "timeslider_returnToPad"]
        ]
      },
    
      "exposeVersion": false,
    
      "loglevel": "INFO",
    
      "logconfig" :
        { "appenders": [
            { "type": "console"
            }
          ]
        }
    }
